name: DeathSwap
main: com.blank038.deathswap.DeathSwap
authors:
  - Blank038
  - DeathSwap
version: 1.0.0-SNAPSHOT
commands:
  deathswap:
    aliases:
      - ds
    description: Command for DeathSwap.